name: docker-compose-test

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and Start Docker Compose services
        run:
          cd docker_compose_test && \
          docker-compose up -d --build

      - name: Wait for service to be ready
        run: sleep 5 

      - name: Check status code
        run: |
          status_code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000)
          if [[ $status_code -ne 200 ]]; then
            echo "Request failed with status code $status_code"
            exit 1
          fi