name: flake8 ⚙️

on: [ push, pull_request ]

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      name: Setup Python ${{ matrix.python-version }}
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install system dependencies 📦
      run: sudo apt-get install -y dh-python devscripts fakeroot debhelper python3-all python3-setuptools
    - name: Install requirements 📦
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements-dev.txt
    - name: run flake8 ⚙️
      run: flake8
